# Generated by Django 6.0.5 on 2026-05-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doacao_item', models.CharField(max_length=200)),
                ('remetente', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18)),
                ('status', models.CharField(choices=[('Recebido', 'Recebido'), ('Processado', 'Processado'), ('Repassado', 'Repassado')], default='Recebido', max_length=20)),
                ('data', models.DateField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
