# Generated by Django 6.0.5 on 2026-05-20 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alimento', 'Alimento'), ('vestuario', 'Vestuário'), ('outro', 'Outro')], max_length=20)),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('processando', 'Processando'), ('repassado', 'Repassado')], default='recebido', max_length=20)),
                ('descricao', models.TextField()),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.destinatario')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doador')),
            ],
        ),
    ]
