# Generated by Django 6.0.5 on 2026-05-25 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='doador',
        ),
        migrations.AlterModelOptions(
            name='doacao',
            options={'ordering': ['-data', '-id']},
        ),
        migrations.RenameField(
            model_name='doacao',
            old_name='data_registro',
            new_name='criado_em',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='data_validade',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='tipo',
        ),
        migrations.AddField(
            model_name='doacao',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doacao',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doacao',
            name='doacao_item',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doacao',
            name='remetente',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doacao',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='status',
            field=models.CharField(choices=[('Recebido', 'Recebido'), ('Repassado', 'Repassado'), ('Processado', 'Processado')], default='Recebido', max_length=20),
        ),
        migrations.DeleteModel(
            name='Destinatario',
        ),
        migrations.DeleteModel(
            name='Doador',
        ),
    ]
