# Generated by Django 6.0.5 on 2026-05-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doacao_tipo_descricao_repasses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='cpf_cnpj',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
